"""Regenerate host/data.js from the docs/ tree + README + AGENTX.md.

Run this from the repo root whenever docs change:

    python host/build_data.py

Emits:
  window.AGENTX_NAV  = [ { name, items: [ { slug, title } ] }, ... ]
  window.AGENTX_DOCS = { slug: { title, markdown, group } }
"""
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT / "docs"
OUT = ROOT / "host" / "data.js"


# (group_label, [(slug, source_path, override_title_or_None), ...])
NAV = [
    ("Home", [
        ("index", None, "Overview"),                # rendered from JS
        ("getting-started", DOCS_DIR / "getting-started.md", None),
    ]),
    ("Concepts", [
        ("concepts/models", DOCS_DIR / "concepts" / "models.md", None),
        ("concepts/tools", DOCS_DIR / "concepts" / "tools.md", None),
        ("concepts/agents", DOCS_DIR / "concepts" / "agents.md", None),
        ("concepts/permissions", DOCS_DIR / "concepts" / "permissions.md", None),
        ("concepts/observability", DOCS_DIR / "concepts" / "observability.md", None),
    ]),
    ("Guides", [
        ("guides/file-agent", DOCS_DIR / "guides" / "file-agent.md", None),
        ("guides/structured-output", DOCS_DIR / "guides" / "structured-output.md", None),
        ("guides/streaming", DOCS_DIR / "guides" / "streaming.md", None),
        ("guides/sessions", DOCS_DIR / "guides" / "sessions.md", None),
        ("guides/mcp", DOCS_DIR / "guides" / "mcp.md", None),
        ("guides/yaml-config", DOCS_DIR / "guides" / "yaml-config.md", None),
        ("guides/custom-tools", DOCS_DIR / "guides" / "custom-tools.md", None),
    ]),
    ("Advanced", [
        ("advanced/memory", DOCS_DIR / "advanced" / "memory.md", None),
        ("advanced/rag", DOCS_DIR / "advanced" / "rag.md", None),
        ("advanced/vector-store-adapters", DOCS_DIR / "advanced" / "vector-store-adapters.md", None),
        ("advanced/prompt-caching", DOCS_DIR / "advanced" / "prompt-caching.md", None),
        ("advanced/parallel-tools", DOCS_DIR / "advanced" / "parallel-tools.md", None),
        ("advanced/supervisor", DOCS_DIR / "advanced" / "supervisor.md", None),
        ("advanced/handoffs", DOCS_DIR / "advanced" / "handoffs.md", None),
        ("advanced/evals", DOCS_DIR / "advanced" / "evals.md", None),
        ("advanced/prompt-optimization", DOCS_DIR / "advanced" / "prompt-optimization.md", None),
        ("advanced/batch-api", DOCS_DIR / "advanced" / "batch-api.md", None),
        ("advanced/trace-viewer", DOCS_DIR / "advanced" / "trace-viewer.md", None),
        ("advanced/production-controls", DOCS_DIR / "advanced" / "production-controls.md", None),
    ]),
    ("Reference", [
        ("reference/api-summary", DOCS_DIR / "reference" / "api-summary.md", None),
    ]),
    ("Cookbook", [
        ("cookbook/patterns", DOCS_DIR / "cookbook" / "patterns.md", None),
        ("cookbook/troubleshooting", DOCS_DIR / "cookbook" / "troubleshooting.md", None),
        ("cookbook/faq", DOCS_DIR / "cookbook" / "faq.md", None),
    ]),
    ("Project", [
        ("readme", ROOT / "README.md", "README (full)"),
        ("agentx-md", ROOT / "AGENTX.md", "AGENTX.md (agent guide)"),
        ("docs-index", DOCS_DIR / "README.md", "Docs index (source)"),
    ]),
]


def infer_title(md: str, fallback: str) -> str:
    for line in md.splitlines():
        m = re.match(r"^\s*#\s+(.+?)\s*$", line)
        if m:
            return m.group(1)
    return fallback


def build():
    docs = {}       # slug -> {title, markdown, group}
    nav_out = []
    missing = []

    for group_name, entries in NAV:
        nav_items = []
        for slug, path, override_title in entries:
            if slug == "index":
                nav_items.append({"slug": slug, "title": override_title or "Overview"})
                docs[slug] = {
                    "title": override_title or "Overview",
                    "markdown": "",
                    "group": group_name,
                }
                continue
            if path is None or not path.exists():
                missing.append((slug, path))
                continue
            md = path.read_text(encoding="utf-8")
            title = override_title or infer_title(md, slug)
            nav_items.append({"slug": slug, "title": title})
            docs[slug] = {"title": title, "markdown": md, "group": group_name}
        nav_out.append({"name": group_name, "items": nav_items})

    if missing:
        print("Missing sources:")
        for slug, path in missing:
            print(f"  - {slug}  ({path})")

    js = (
        "/* Auto-generated by host/build_data.py. Do not edit. */\n"
        "window.AGENTX_NAV = "
        + json.dumps(nav_out, ensure_ascii=False, indent=2)
        + ";\n\n"
        "window.AGENTX_DOCS = "
        + json.dumps(docs, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)} "
        f"({len(docs)} pages, {sum(len(g['items']) for g in nav_out)} nav entries)"
    )


if __name__ == "__main__":
    build()
